Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "95"]
    v.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
    v.memory = 4096
    v.cpus = 8
  end
end
